# Generated by Django 3.2.4 on 2021-08-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion_envio', models.CharField(max_length=250)),
                ('nombre_receptor', models.CharField(max_length=100)),
                ('direccion_receptor', models.CharField(max_length=100)),
            ],
        ),
    ]
