# Generated by Django 3.2.4 on 2021-08-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('mensajeria', 'Mensajería'), ('paqueteria', 'Paquetería')], max_length=100),
        ),
    ]
